<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE persoane [
<!ELEMENT persoane (persoana,adresa)>
<!ELEMENT persoana (nume,prenume,varsta)>
<!ATTLIST persoana id CDATA "0">
<!ELEMENT adresa (strada,numar,localitate,judet,tara)>
<!ELEMENT nume (#PCDATA)>
<!ELEMENT prenume (#PCDATA)>
<!ELEMENT varsta (#PCDATA)>

<!ELEMENT strada (#PCDATA)>
<!ELEMENT numar (#PCDATA)>
<!ELEMENT localitate (#PCDATA)>
<!ELEMENT judet (#PCDATA)>
<!ELEMENT tara (#PCDATA)>
]>
<persoane>
    
    <persoana id="1">
        <nume>Popescu</nume>
        <prenume>Ion</prenume>
        <varsta>23</varsta>

    </persoana>

    <adresa>
        <strada>Smaraldului</strada>
        <numar>13</numar>
        <localitate>Valea Hamsterului</localitate>
        <judet>Iasi</judet>
        <tara>Romania</tara>
    </adresa>

</persoane>